{% set version = "0.2.0" %}
{% set core_version = ">=0.2.0,<0.3.0" %}

package:
  name: jupyterlite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlite/jupyterlite-{{ version }}.tar.gz
  sha256: 953bd8c6a2d976d735f9f416fdba17da2d0b6daee6d6471481a08563a166d3df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python >=3.8
  run:
    - jupyterlite-core {{ core_version }}
    - jupyterlite-javascript-kernel {{ core_version }}
    - python >=3.8

test:
  imports:
    - jupyterlite
  commands:
    - pip check
    - jupyter lite --version
    - jupyter lite --help
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
