{% set core_version = ">=0.1.2,<0.2.0" %}
{% set version = "0.1.3" %}
{% set core_version = ">=0.1.2,<0.2.0" %}

package:
  name: jupyterlite
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/j/jupyterlite/jupyterlite-{{ version }}.tar.gz
    sha256: 20eca801bd05d12aa1af7eaa5a0b7b0195a26dd0da7e04fcc244fc04ae5de701

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python >=3.8
  run:
    - jupyterlite-core {{ core_version }}
    - jupyterlite-javascript-kernel {{ core_version }}
    - jupyterlite-pyodide-kernel >=0.0.6
    - python >=3.8

test:
  imports:
    - jupyterlite
  commands:
    - pip check
    - jupyter lite --version
    - jupyter lite --help
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
