{% set version = "0.1.0" %}
{% set core_version = ">=0.1.0,<0.2.0" %}

package:
  name: jupyterlite
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/j/jupyterlite/jupyterlite-{{ version }}.tar.gz
    sha256: 6e9949bc51247368bea8a0136256694255ace315e6e057020d29b36fe92c3c38
  - fn: jupyterlite-{{ version }}-LICENSE
    url: https://raw.githubusercontent.com/jupyterlite/jupyterlite/v{{ version }}/LICENSE
    sha256: 502e99ce4df4cd9fe0b14f6acb7c95553a5dd9615982fb246c233330f317eff4
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python >=3.8
  run:
    - jupyterlite-core {{ core_version }}
    - jupyterlite-javascript-kernel {{ core_version }}
    - jupyterlite-pyodide-kernel >=0.0.6
    - python >=3.8

test:
  imports:
    - jupyterlite
  commands:
    - pip check
    - jupyter lite --version
    - jupyter lite --help
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  # TODO: use as-packaged license https://github.com/jupyterlite/jupyterlite/pull/1039
  license_file: jupyterlite-{{ version }}-LICENSE
  doc_url: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
