{% set version = "0.4.1" %}
{% set core_version = ">=" ~ version ~ ",<0.5.0" %}

package:
  name: jupyterlite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlite/jupyterlite-{{ version }}.tar.gz
  sha256: 1eeb272ecee46af4c4154ec62a0e1fbce55dcc698e6ca7aa0a188c94a642186e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.6.3,<2
    - pip
    - python >=3.8
  run:
    - jupyterlite-core {{ core_version }}
    - python >=3.8

test:
  imports:
    - jupyterlite
  commands:
    - pip check
    - jupyter lite --version
    - jupyter lite --help
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: JupyterLite metapackage
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://jupyterlite.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
